In [1]:
import pandas as pd

# Read .xpt file
df_drugs = pd.read_sas('DUQ_J.xpt')
df_income = pd.read_sas('INQ_J.xpt')

# print(df_drugs.head())
# print(df_income.iloc[:, :20].head())

In [2]:
income_known = df_income[df_income['IND235'] != 99]
income_known = income_known[income_known['IND235'] != 77]

In [3]:
druguse_known = df_drugs[df_drugs['DUQ200'] != 2]
druguse_known = druguse_known.dropna(subset='DUQ200')
druguse_known

,SEQN,DUQ200,DUQ210,DUQ211,DUQ213,DUQ215Q,DUQ215U,DUQ217,DUQ219,DUQ220Q,...,DUQ380A,DUQ380B,DUQ380C,DUD380F,DUQ390,DUQ400Q,DUQ400U,DUQ410,DUQ420,DUQ430
4,93712.0,1.0,18.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
8,93717.0,1.0,14.0,1.0,16.0,4.0,3.0,4.0,2.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
14,93728.0,1.0,40.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
15,93729.0,1.0,12.0,1.0,19.0,1.0,1.0,5.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
19,93738.0,1.0,17.0,1.0,17.0,9.0,4.0,4.0,2.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4559,102923.0,1.0,18.0,2.0,NaN,NaN,NaN,NaN,NaN,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
4562,102934.0,1.0,20.0,1.0,20.0,20.0,4.0,4.0,1.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
4563,102935.0,1.0,23.0,2.0,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
4568,102949.0,1.0,18.0,1.0,18.0,15.0,1.0,3.0,1.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
4571,102956.0,1.0,16.0,2.0,NaN,NaN,NaN,NaN,NaN,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0

In [4]:
merged_df = druguse_known.merge(income_known, on='SEQN')
merged_df.to_csv('NHANES1718.csv', index=False)
merged_df

,SEQN,DUQ200,DUQ210,DUQ211,DUQ213,DUQ215Q,DUQ215U,DUQ217,DUQ219,DUQ220Q,...,INQ090,INQ132,INQ140,INQ150,IND235,INDFMMPI,INDFMMPC,INQ300,IND310,INQ320
0,93712.0,1.0,18.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,...,2.0,2.0,2.0,2.0,4.0,7.600000e-01,1.0,2.0,1.0,1.0
1,93717.0,1.0,14.0,1.0,16.0,4.0,3.0,4.0,2.0,4.0,...,2.0,2.0,2.0,2.0,1.0,5.397605e-79,1.0,2.0,1.0,4.0
2,93728.0,1.0,40.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,...,2.0,2.0,1.0,2.0,12.0,5.000000e+00,3.0,1.0,NaN,1.0
3,93729.0,1.0,12.0,1.0,19.0,1.0,1.0,5.0,3.0,1.0,...,1.0,2.0,2.0,2.0,3.0,8.700000e-01,1.0,2.0,1.0,1.0
4,93738.0,1.0,17.0,1.0,17.0,9.0,4.0,4.0,2.0,9.0,...,2.0,2.0,2.0,2.0,8.0,1.460000e+00,2.0,2.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1553,102923.0,1.0,18.0,2.0,NaN,NaN,NaN,NaN,NaN,25.0,...,2.0,2.0,2.0,2.0,8.0,2.350000e+00,3.0,2.0,1.0,1.0
1554,102934.0,1.0,20.0,1.0,20.0,20.0,4.0,4.0,1.0,20.0,...,2.0,2.0,2.0,2.0,8.0,2.310000e+00,3.0,2.0,1.0,1.0
1555,102935.0,1.0,23.0,2.0,NaN,NaN,NaN,NaN,NaN,4.0,...,2.0,2.0,1.0,2.0,3.0,8.500000e-01,1.0,1.0,NaN,2.0
1556,102949.0,1.0,18.0,1.0,18.0,15.0,1.0,3.0,1.0,15.0,...,2.0,2.0,2.0,1.0,6.0,9.200000e-01,1.0,2.0,1.0,1.0
1557,102956.0,1.0,16.0,2.0,NaN,NaN,NaN,NaN,NaN,20.0,...,2.0,2.0,2.0,1.0,7.0,1.560000e+00,2.0,2.0,1.0,1.0